# Generated by Django 4.1.2 on 2022-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='aadhar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='passport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
