# Generated by Django 4.1.2 on 2022-11-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_customer_detail_aadhar_customer_detail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/upload/default.png', upload_to='static/images/upload/'),
        ),
    ]
