# Generated by Django 4.1.2 on 2022-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_customer_detail_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
