# Generated by Django 4.1.2 on 2022-11-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_packages_alter_customer_detail_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
