# Generated by Django 4.1.2 on 2022-11-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_packages_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
