# Generated by Django 4.1.2 on 2022-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_packages_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
    ]
