# Generated by Django 4.1.2 on 2022-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_packages_image_height_packages_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='packages',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
