# Generated by Django 4.1.2 on 2022-11-11 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0011_alter_customer_detail_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('persons', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('agent', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_mobile', models.IntegerField(blank=True, null=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.packages')),
                ('username', models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.booking')),
            ],
        ),
    ]
