# Generated by Django 4.1.2 on 2022-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_booking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package_id',
            field=models.IntegerField(),
        ),
    ]
