# Generated by Django 4.1.2 on 2022-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_booking_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking_id',
            field=models.IntegerField(),
        ),
    ]
