# Generated by Django 4.1.2 on 2022-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_alter_passenger_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
