# Generated by Django 4.1.2 on 2022-11-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_booking_startdate_alter_booking_agent_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
