# Generated by Django 4.1.2 on 2022-11-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_remove_booking_package_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='age',
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='aadhar',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='gender',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='mobile',
            field=models.CharField(default='+91 00000-00000', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='passport',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
