# Generated by Django 4.1.2 on 2022-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_remove_customer_detail_age_customer_detail_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
