# Generated by Django 4.1.2 on 2022-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_alter_customer_detail_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsbar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='pics/default.png', upload_to='pics')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=25)),
                ('heading', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
