# Generated by Django 4.1.2 on 2022-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_alter_customer_detail_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='avatar',
            field=models.ImageField(blank=True, default='pics/default.jpg', upload_to='pics'),
        ),
    ]
